missing GSD, snapshot, sph and nsearch

diff --git a/hoomd-blue/sphinx-doc/tutorial/.github/workflows/test.yml b/hoomd-blue/sphinx-doc/tutorial/.github/workflows/test.yml
--- a/hoomd-blue/sphinx-doc/tutorial/.github/workflows/test.yml
+++ b/hoomd-blue/sphinx-doc/tutorial/.github/workflows/test.yml
@@ -13,6 +13,7 @@ on:
   push:
     branches:
       - "trunk"
+      - "trunk-major"
 
   # Trigger on request.
   workflow_dispatch:
@@ -28,7 +29,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: "Use jetstream2-admin/start"
-      uses: glotzerlab/jetstream2-admin/start@v1.2.1
+      uses: glotzerlab/jetstream2-admin/start@v1.2.2
       with:
         OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
         OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
@@ -47,10 +48,10 @@ jobs:
 
     # build the HOOMD trunk-minor branch to test the tutorials on the latest version
     - name: Checkout
-      uses: actions/checkout@v3.3.0
+      uses: actions/checkout@v3.6.0
       with:
         path: hoomd
-        ref: trunk-minor
+        ref: trunk-major
         repository: glotzerlab/hoomd-blue
         submodules: true
     - name: Make build directory
@@ -64,7 +65,7 @@ jobs:
         -DENABLE_MPI=off
         -DENABLE_TBB=off
         -DBUILD_TESTING=off
-        -DBUILD_JIT=off
+        -DENABLE_LLVM=on
         ../
       working-directory: hoomd/build
     - name: Compile
@@ -77,22 +78,34 @@ jobs:
 
     # clone the tutorials and run them
     - name: Checkout
-      uses: actions/checkout@v3.3.0
+      uses: actions/checkout@v3.6.0
       with:
         path: notebooks
     - name: List notebooks
       run: ls **/*.ipynb
       working-directory: notebooks
     - name: Execute notebooks
-      run: jupyter nbconvert --execute --inplace **/*.ipynb
+      run: 'for i in */; do echo "Running notebooks in: $i" && jupyter nbconvert --execute --inplace $i/*.ipynb || exit 1; done'
       working-directory: notebooks
       env:
         PYTHONPATH: ${{ github.workspace }}/hoomd/build
 
+    # This check is very basic, but we don't want to use `python -W error` as it will also catch any
+    # warnings generated inside nbconvert and its dependencies.
+    - name: Check for warnings
+      run: |
+        has_warnings=0
+        for file in **/*.ipynb
+        do
+          grep Warning $file && echo "::error file=${file}::Has deprecation warnings" && has_warnings=1
+        done
+        exit ${has_warnings}
+      working-directory: notebooks
+
     # notify developers if the scheduled check fails
     - name: Slack notification
       if: ${{ github.event_name == 'schedule' && (failure() || cancelled()) }}
-      uses: 8398a7/action-slack@v3.15.0
+      uses: 8398a7/action-slack@v3.15.1
       with:
         status: ${{ job.status }}
         fields: workflow,job,message,commit
